const express = require('express');
const c = require('../controllers/build.controller');
const { authenticate, authorize } = require('../middlewares/authorization.middleware');
const { positiveId } = require('../middlewares/validation.middleware');
const router = express.Router();
router.use(authenticate);
router.get('/', c.list);
router.get('/components', authorize('admin', 'staff', 'ADMIN', 'STAFF'), c.components);
router.get('/:id', positiveId('id'), c.find);
router.post('/', authorize('admin', 'staff', 'ADMIN', 'STAFF'), c.save);
router.put('/:id', positiveId('id'), authorize('admin', 'staff', 'ADMIN', 'STAFF'), c.save);
router.patch('/:id/status', positiveId('id'), authorize('admin', 'staff', 'ADMIN', 'STAFF'), c.status);
router.delete('/:id', positiveId('id'), authorize('admin', 'staff', 'ADMIN', 'STAFF'), c.remove);
module.exports = router;
