const express = require('express');
const categoryRouter = require('./category.router');
const roleRouter = require('./role.router');
const userRouter = require('./user.router');
const productRouter = require('./product.router');
const cartRouter = require('./cart.router');
const voucherRouter = require('./voucher.router');
const buildRouter = require('./build.router');
const customBuildRouter = require('./custom-build.router');
const warrantyRouter = require('./warranty.router');
const notificationRouter = require('./notification.router');
const orderRouter = require('./order.router');
const paymentRouter = require('./payment.router');
const inventoryRouter = require('./inventory.router');
const adressRouter = require('./address.router');
const brandsRouter = require('./brand.router');
const ProductImageRouter = require('./productImage.router');
const ProductVariantRouter = require('./productVariant.router');
const favoriteRouter = require('./favorite.router');
const reviewRouter = require('./review.router');
const checkoutRouter = require('./checkout.router');
const catalogRouter = require('./catalog.router');
const promotionRouter = require('./promotion.router');
const pcBuilderRouter = require('./pc-builder.router');
const laptopUpgradeRouter = require('./laptop-upgrade.router');
const router = express.Router();

router.use('/categories', categoryRouter);
router.use('/roles', roleRouter);
router.use('/users', userRouter);
router.use('/products', productRouter);
router.use('/cart', cartRouter);
router.use('/vouchers', voucherRouter);
router.use('/build-templates', buildRouter);
router.use('/custom-builds', customBuildRouter);
router.use('/warranties', warrantyRouter);
router.use('/notifications', notificationRouter);
router.use('/orders', orderRouter);
router.use('/admin/orders', orderRouter);
router.use('/', paymentRouter);
router.use('/inventory', inventoryRouter);
router.use('/addresses', adressRouter);
router.use('/brands', brandsRouter);
router.use('/product-images', ProductImageRouter);
router.use('/product-variants', ProductVariantRouter);
router.use('/favorites', favoriteRouter);
router.use('/reviews', reviewRouter);
router.use('/checkout', checkoutRouter);
router.use('/catalog', catalogRouter);
router.use('/promotions', promotionRouter);
router.use('/pc-builder', pcBuilderRouter);
router.use('/laptops', laptopUpgradeRouter);
module.exports = router;
